postgres_rpm_url: http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-3.noarch.rpm

# Certs under `files` dir needs to be replaced with proper ones
lims_cert_prefix: star_snpseq_medsci_uu_se

miniconda_src: /tmp/Miniconda-latest-Linux-x86_64.sh
miniconda_dest: /usr/local/miniconda
miniconda_url: https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh

lims_venv: /opt/gls/clarity/users/glsai/.conda/envs/clarity/
