# This file should preferably be encrypted with ansible-vault

lims_user: 
    name: clarity
    password: sha-512 hashed password

gls_users: 
    - name: glsjboss
      password: sha-512 hashed password
    - name: glsai
      password: sha-512 hashed password
    - name: glsftp
      password: sha-512 hashed password


