# This file should preferably be encrypted with ansible-vault

# Lims app settings
lims_rpm_username: upstream-clarity-ftp-username
lims_rpm_password_clarity4: upstream-clarity-ftp-unencrypted-password1
lims_rpm_password_clarity_hiseq: upstream-clarity-ftp-unencrypted-password2
lims_rpm_password_clarity_hiseqxfile: upstream-clarity-ftp-unencrypted-password3
lims_rpm_password_clarity_miseq: upstream-clarity-ftp-unencrypted-password4
lims_rpm_password_claritylims_integrations: upstream-clarity-ftp-unencrypted-password4

lims_api_user: apiuser
lims_api_password: unencrypted-lims-api-password

lims_samba_user: samba-username
lims_samba_password: unencrypted-samba-password
