
- name: add postgresql from official rpm package
  yum: name="{{ postgres_rpm_url }}" state=present

- name: install postgres server
  yum: name="postgresql94-server" state=present

- name: install postgres adaptor for python
  yum: name="python-psycopg2" state=present

- name: create a new db cluster (will be skipped if data already exists)
  shell: service postgresql-9.4 initdb
  args:
    warn: false
  tags: skip_ansible_lint

- name: enable postgresql service and start the db
  service: name="postgresql-9.4" enabled=yes state=started
