- name: restart postgres
  service:
    name: postgresql-9.4
    state: restarted

- name: restart jboss
  service:
    name: jboss
    state: restarted

- name: restart httpd
  service:
    name: httpd
    state: restarted
